tunnel: e3c33632-f7db-426b-b4fd-14ee9df0b024
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: asus.vocbilliard.online
    service: http://voc_frontend:3000
  - hostname: api.asus.vocbilliard.online
    service: http://voc_backend:4000
  - hostname: mqtt.asus.vocbilliard.online
    service: http://voc_mosquitto:8083
  - service: http_status:404
