tunnel: 9af9600e-6753-4dd1-a078-1f4f163b38bb
credentials-file: C:\Users\tirta\.cloudflared\9af9600e-6753-4dd1-a078-1f4f163b38bb.json

ingress:
  - hostname: enkatextile.co.id
    service: http://127.0.0.1:8080
  - hostname: enkatextile.vocbilliard.online
    service: http://127.0.0.1:8080
  - hostname: admin.vocbilliard.online
    service: http://127.0.0.1:3000
  - hostname: api.vocbilliard.online
    service: http://127.0.0.1:4000
  - hostname: mqtt.vocbilliard.online
    service: http://127.0.0.1:8083
  - service: http_status:404
