@echo off
chcp 65001 >nul 2>&1
title VOC Billiard - Quick Installer

:: ═══════════════════════════════════════════════════════════════════════════
:: VOC BILLIARD SYSTEM - Quick Installation Script
:: Compatible with Windows 10/11
:: Requires: Docker Desktop
:: ═══════════════════════════════════════════════════════════════════════════

:START
cls
echo.
echo  ╔════════════════════════════════════════════════════════════════════════╗
echo  ║                                                                        ║
echo  ║              VOC BILLIARD - INSTALLATION WIZARD                        ║
echo  ║              Multi-Location Ready - Docker Deployment                 ║
echo  ║                                                                        ║
echo  ╚════════════════════════════════════════════════════════════════════════╝
echo.

:: ─── Check Administrator ───
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo [INFO] Tip: Klik kanan Command Prompt ^> Run as Administrator
    echo.
)

:: ─── Check Docker ───
echo [1/7] Memeriksa Docker...
docker --version >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo  ╔════════════════════════════════════════════════════════════════╗
    echo  ║  [ERROR] Docker tidak ditemukan!                               ║
    echo  ║                                                                ║
    echo  ║  Langkah:                                                       ║
    echo  ║  1. Download Docker Desktop: https://docker.com/get-started   ║
    echo  ║  2. Install dan restart komputer                               ║
    echo  ║  3. Pastikan Docker Running di system tray                      ║
    echo  ║                                                                ║
    echo  ╚════════════════════════════════════════════════════════════════╝
    echo.
    pause
    exit /b 1
)
echo  [OK] Docker ditemukan:
docker --version
echo.

:: ─── Create directories ───
echo [2/7] Membuat folder konfigurasi...
mkdir mosquitto\config 2>nul
mkdir mosquitto\data 2>nul
mkdir mosquitto\logs 2>nul
mkdir backend\storage 2>nul
mkdir backend\logs 2>nul
echo  [OK] Folder dibuat
echo.

:: ─── Create .env ───
echo [3/7] Membuat file konfigurasi...
if not exist ".env" (
    copy ".env.example" ".env"
    echo  [INFO] File .env telah dibuat
    echo  [IMPORTANT] Silakan edit file .env dan isi:
    echo            - LOCATION_ID
    echo            - LOCATION_NAME
    echo            - DB_PASSWORD
    echo            - GAS_WEBAPP_URL
    echo            - GAS_SECRET
    echo.
) else (
    echo  [OK] File .env sudah ada
)
echo.

:: ─── Create MQTT password file ───
echo [4/7] Setup MQTT authentication...
if not exist "mosquitto\config\pwfile" (
    echo # Mosquitto password file > mosquitto\config\pwfile
    echo # Generated by VOC Billiard Installer >> mosquitto\config\pwfile
    echo [INFO] Password file dibuat (anonymous allowed)
)
echo  [OK] MQTT config siap
echo.

:: ─── Pull Docker images ───
echo [5/7] Download images (pertama kali akan download, ini normal)...
echo  Downloading: postgres:15-alpine
docker pull postgres:15-alpine >nul 2>&1
echo  Downloading: redis:7-alpine
docker pull redis:7-alpine >nul 2>&1
echo  Downloading: eclipse-mosquitto:2
docker pull eclipse-mosquitto:2 >nul 2>&1
echo  Downloading: node:20-alpine (backend)
docker pull node:20-alpine >nul 2>&1
echo  [OK] Images siap
echo.

:: ─── Build Docker images ───
echo [6/7] Build aplikasi...
docker-compose build --parallel 2>nul
if %errorlevel% neq 0 (
    echo  [WARNING] Build dengan parallel gagal, mencoba sequential...
    docker-compose build
)
echo  [OK] Aplikasi ter-build
echo.

:: ─── Start services ───
echo [7/7] Memulai layanan...
echo Stopping existing containers (jika ada)...
docker-compose down >nul 2>&1
echo  Starting services...
docker-compose up -d
echo  [OK] Services dimulai
echo.

:: ─── Wait for services ───
echo.
echo  Menunggu services ready...
timeout /t 30 /nobreak >nul

:: ─── Check status ───
echo.
echo  ╔════════════════════════════════════════════════════════════════════════╗
echo  ║                      STATUS CHECK                                      ║
echo  ╚════════════════════════════════════════════════════════════════════════╝
echo.

docker-compose ps
echo.

:: ─── Check logs for errors ───
echo  Memeriksa log untuk error...
docker-compose logs --tail=20 2>&1 | findstr /i "error Error ERROR" > temp_log.txt
if %errorlevel% equ 0 (
    echo  [WARNING] Ada potential error di log. Check temp_log.txt
) else (
    echo  [OK] Tidak ada error critical di log
)
del temp_log.txt 2>nul
echo.

:: ─── Success Message ───
echo.
echo  ╔════════════════════════════════════════════════════════════════════════╗
echo  ║                                                                        ║
echo  ║              INSTALLATION COMPLETE!                                   ║
echo  ║                                                                        ║
echo  ╚════════════════════════════════════════════════════════════════════════╝
echo.
echo  ┌────────────────────────────────────────────────────────────────────┐
echo  │  AKSES SISTEM:                                                      │
echo  │                                                                     │
echo  │  Frontend:     http://localhost:3000                               │
echo  │  Backend API:  http://localhost:4000                                │
echo  │  MQTT:         localhost:1883                                      │
echo  │  MQTT WS:      localhost:8083                                      │
echo  │  PostgreSQL:   localhost:5432                                       │
echo  │  Redis:        localhost:6379                                       │
echo  │                                                                     │
echo  └────────────────────────────────────────────────────────────────────┘
echo.
echo  ┌────────────────────────────────────────────────────────────────────┐
echo  │  LANGKAH SELANJUTNYA:                                               │
echo  │                                                                     │
echo  │  1. [WAJIB] Edit file .env:                                         │
echo  │       - LOCATION_ID (unik per client)                               │
echo  │       - LOCATION_NAME                                               │
echo  │       - DB_PASSWORD (ganti password baru!)                          │
echo  │       - GAS_WEBAPP_URL (dari setup GAS)                            │
echo  │       - GAS_SECRET (samakan dengan di GAS)                          │
echo  │                                                                     │
echo  │  2. [WAJIB] Setup Google Apps Script:                               │
echo  │       - Buat spreadsheet baru                                      │
echo  │       - Pasang GAS code dari backend/src/external-sync/              │
echo  │       - Deploy sebagai Web App                                     │
echo  │       - Copy URL ke GAS_WEBAPP_URL di .env                         │
echo  │                                                                     │
echo  │  3. [WAJIB] Restart services:                                       │
echo  │       docker-compose down && docker-compose up -d                  │
echo  │                                                                     │
echo  │  4. [OPSIONAL] Flash ESP32 firmware dengan IP baru                   │
echo  │                                                                     │
echo  └────────────────────────────────────────────────────────────────────┘
echo.
echo  Commands utile:
echo    docker-compose logs -f       ^> Lihat log real-time
echo    docker-compose restart       ^> Restart semua services
echo    docker-compose down          ^> Stop semua services
echo    docker-compose ps           ^> Status services
echo.
pause