# Mosquitto MQTT Broker Configuration

# Log settings
log_type all
log_dest stdout

# ---- TCP Listener (for backend NestJS & ESP32) ----
listener 1883 0.0.0.0
socket_domain ipv4
allow_anonymous true

# ---- WebSocket Listener (for frontend browser) ----
listener 8083 0.0.0.0
protocol websockets
# socket_domain ipv4
allow_anonymous true

# Security & Performance
max_connections -1
set_tcp_nodelay true
persistence false
