tunnel: b627de5b-1d08-418b-9f50-76e7d5242af5
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: panteka.vocbilliard.online
    service: http://voc_frontend:3000
  - hostname: api-panteka.vocbilliard.online
    service: http://voc_backend:4000
  - hostname: mqtt-panteka.vocbilliard.online
    service: http://voc_mosquitto:8083
  - service: http_status:404
