tunnel: fea10d1e-af37-4787-9c08-810668036cc5
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ballistic.vocbilliard.online
    service: http://voc_frontend:3000
  - hostname: api-ballistic.vocbilliard.online
    service: http://voc_backend:4000
  - hostname: mqtt-ballistic.vocbilliard.online
    service: http://voc_mosquitto:8083
  - service: http_status:404
