tunnel: 0e06ea1d-2e5f-4614-bad0-22473098e7b6
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: bogor.vocbilliard.online
    service: http://voc_frontend:3000
  - hostname: api-bogor.vocbilliard.online
    service: http://voc_backend:4000
  - hostname: mqtt-bogor.vocbilliard.online
    service: http://voc_mosquitto:8083
  - service: http_status:404
