tunnel: 133ed63d-2a57-4a8d-b0f3-5e8334b40651
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: scuff.vocbilliard.online
    service: http://voc_frontend:3000
  - hostname: api-scuff.vocbilliard.online
    service: http://voc_backend:4000
  - hostname: mqtt-scuff.vocbilliard.online
    service: http://voc_mosquitto:8083
  - service: http_status:404
